### ISSUE TITLE
Tweak the canned filters

### ISSUE THREAD

**Issue by cellio** [mattjbrent/mattjbrent.github.io#3]
The baked-in filters (which yes I know are just placeholders) include one that's keyed on accepted answers.  Codidact doesn't have answer acceptance, so let's remove that distraction from the mockup.

I was going to suggest replacing it with "exclude questions with more than 3 answers" (just as an arbitrary point), then realized that the first one could be generalized.  What do you think about "exclude questions with __ answers", where the __ is a textbox where you can typa  number?

I realize this is a mockup and the exact filters don't matter much right now, but if we can make them resonate a little better for people, that's cool. :-)

**Comment by mattjbrent** [comment]
No i think resonation (*!) is good! its a relatively simple change

**Comment by mattjbrent** [comment]
ive just removed and replaced with 3 for now. This could be a discussion point as i think these could be configurable with the filter creation tool we talked about in another issue. we only mentioned and/or but I was thinking it would be cool to create filters and have them toggleable here and include multiple queries you can select on the fly rather than using a dropdown box
